server:
  port: 8080
   
jwt.secret: secret
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bms
    username: root
    password: pass@word1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
